<a href="https://colab.research.google.com/github/aditi-tawade-ai/aditi-tawade-ai/blob/main/Notebook/Day16_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [ ]:
import numpy as np

In [ ]:
#1D array
a=np.array([20,100,45,36,80])
a

array([ 20, 100,  45,  36,  80])

In [ ]:
a=np.array([20,520,45])
a

array([ 20, 520,  45])

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>

In [ ]:
np.__version__

'2.0.2'

In [ ]:
a

array([ 20, 100,  45,  36,  80])

In [ ]:
#Find max  number
print(a.max())

100


In [ ]:
a.min()

np.int64(20)

In [ ]:
#length of element
a.size

5

In [ ]:
#Dimension
a.ndim

1

In [ ]:
type(a)

numpy.ndarray

In [ ]:
#Q. what is a type of numpy array?
# ndarry is type of numpy
#ndarray says that we can use multidimentional array

In [ ]:
b=np.array([[10,20,1],
            [-1,5,9],
            [7,40,2]])
b

array([[10, 20,  1],
       [-1,  5,  9],
       [ 7, 40,  2]])

In [ ]:
b.ndim

2

In [ ]:
#to check number of rows and coloumn
b.shape   #(rows,column)

(3, 3)

In [ ]:
#addition of all elements
print(b.sum())

93


In [ ]:
#column wise addition
print(b.sum(axis=0))

[16 65 12]


In [ ]:
print(b.sum(axis=1))

[31 13 49]


In [ ]:
#Assignment: b.min(),b.max(),b.mean(),b.std()

In [ ]:
import numpy as np
c=np.array([[10,20,1],
            [-1,5,9],
            [7,40,2]])

print(c.min(axis=0))    #minimum value  0=column,1=rows

[-1  5  1]


In [ ]:
c=np.array([[10,20,1],
            [-1,5,9],
            [7,40,2]])

print(c.max(axis=0))    #minimum value

[10 40  9]


In [ ]:
print(c.mean(axis=1))

[10.33333333  4.33333333 16.33333333]


In [ ]:
print(c.mean(axis=0))

[ 5.33333333 21.66666667  4.        ]


In [ ]:
print(c.std(axis=0))

[ 4.64279609 14.33720878  3.55902608]


In [ ]:
help(c.std)

Help on built-in function std:

std(...) method of numpy.ndarray instance
    a.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)

    Returns the standard deviation of the array elements along given axis.

    Refer to `numpy.std` for full documentation.

    See Also
    --------
    numpy.std : equivalent function



In [ ]:
a.ndim

1

In [ ]:
b.ndim

2

# **Different ways of creating numpy arrays**

In [ ]:
#numpy array with random no
np.random.random(4)

array([0.52948975, 0.24215314, 0.16576634, 0.19909585])

In [ ]:
c=np.random.random((4,4))
c

array([[0.27623508, 0.75829661, 0.2878376 , 0.45275463],
       [0.86234412, 0.85330788, 0.63119835, 0.51649323],
       [0.11673365, 0.02263817, 0.67582873, 0.66020829],
       [0.63930159, 0.59818085, 0.49489114, 0.1785347 ]])

In [ ]:
c.ndim

2

In [ ]:
#3D - block,row,column
np.random.random((2,2,2))

array([[[0.74572196, 0.31966376],
        [0.69521851, 0.32006626]],

       [[0.03648339, 0.07237553],
        [0.94130034, 0.86935224]]])

In [ ]:
#generate array with sequence of num
c=np.arange(24)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
c.size

24

In [ ]:
#convert from 1D to 2D
# use reshape() which is temp
# use resize() for permanant
# so for 2d we need 2 nums which multiplied gives the no. we want ie. 24
# 2 nos. should be equal to the total no. of elements
#6x4,8x3,12x2,1x24
c.reshape((6,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
c.reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [ ]:
c.reshape(1,16)

ValueError: cannot reshape array of size 24 into shape (1,16)

In [ ]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
#resize for permt
#for permanent operation we do not get output but it is performed
c.resize((3,8))

In [ ]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
c.shape

(3, 8)

In [ ]:
#convert nD to 1D---> use ravel()-->temp
#ravel converts nD to 1D
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
# generate array with sequence of numbers
c=np.arange(25)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
c.size

25

In [ ]:
#5x5,25x1
c.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
c.resize((5,5))

In [ ]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
c.shape

(5, 5)

In [ ]:
#convert nD to 1D
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])