<a href="https://colab.research.google.com/github/aditi-tawade-ai/aditi-tawade-ai/blob/main/Notebook/Day17_NumPy_operatn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Operarions**

In [ ]:
#create an numpy array of 4x4 zeros
import numpy as np
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.full((4,4),1)  #here we can gie any value we want
#no string because it gives dtype as unique

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full((4,4),0,dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
np.full((4,4),-11,dtype=float)

array([[-11., -11., -11., -11.],
       [-11., -11., -11., -11.],
       [-11., -11., -11., -11.],
       [-11., -11., -11., -11.]])

In [ ]:
#create a numpy array of 4x4 with diagonal elements as true and non diagonal elements as false
np.identity(4)  #square matrix-2D -->[[]]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#in python except 0 & none,[],() everything is true
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
bool('adi')

True

In [ ]:
#create a numpy array of 4x4 with diagonal elements as false and non diagonal elements as true
~np.identity(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [ ]:
#access diagonal elements of numpy array
s=np.identity(4)
s.diagonal()

array([1., 1., 1., 1.])

In [ ]:
~np.identity(4,dtype=int)

array([[-2, -1, -1, -1],
       [-1, -2, -1, -1],
       [-1, -1, -2, -1],
       [-1, -1, -1, -2]])

# **Numpy Slicing and indexing**

In [ ]:
x=np.arange(24).reshape((6,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[4]  #using index we can access one row at a time

array([16, 17, 18, 19])

In [ ]:
x[3][2] #row with element index

np.int64(14)

In [ ]:
x[4][3]

np.int64(19)

In [ ]:
x[2][2]

np.int64(10)

In [ ]:
x[2,1]

np.int64(9)

In [ ]:
x[5,2]

np.int64(22)

In [ ]:
x[2,3],[1,3]

(np.int64(11), [1, 3])

In [ ]:
#replace 15 by 50
x[3,3]=50
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[::-2]

array([[20, 21, 22, 23],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7]])

In [ ]:
#access more rows
x[:]  #[start_index:stop_index]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [ ]:
x[-3:]   #last 3 rows

array([[12, 13, 14, 50],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
x[::-3]   #steping -3

array([[20, 21, 22, 23],
       [ 8,  9, 10, 11]])

In [ ]:
# column operations

x[-2:,-2:]   #[row,column]

array([[18, 19],
       [22, 23]])

In [ ]:
x[1:3,1:3]   #start row and stop    next start column stop column

array([[ 5,  6],
       [ 9, 10]])